name: test_coverage

on: [pull_request]
#run specific jobs when specific files are updated.
#https://github.community/t/how-to-execute-jobs-if-folder-updated-recursive/117344/5

jobs:
  check:
    name: Check changed files
    outputs:
      database_run_job: ${{ steps.check_files.outputs.database_run_job }}
      functions_run_job: ${{ steps.check_files.outputs.functions_run_job }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: check files
        id: check_files
        env:
          pr_branch: ${{ github.event.pull_request.head.ref }}
        run: ./scripts/get_updated_files.sh
  pod-lib-lint-database:
    # Don't run on private repo unless it is a PR.
    needs: check
    if: github.repository == 'Firebase/firebase-ios-sdk' && needs.check.outputs.database_run_job == 'true'
    runs-on: macOS-latest

    strategy:
      matrix:
        target: [ios, tvos, macos]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Bundler
      run: scripts/setup_bundler.sh

    - name: Build and test
      env:
        SDK: database
      run: |
        if [ -d "/Users/runner/Library/Developer/Xcode/DerivedData" ]; then
        rm -r /Users/runner/Library/Developer/Xcode/DerivedData/*
        fi
        scripts/third_party/travis/retry.sh scripts/pod_lib_lint.rb FirebaseDatabase.podspec --platforms=${{ matrix.target }} --test-specs=unit
        find /Users/runner/Library/Developer/Xcode/DerivedData -type d -regex ".*/.*\.xcresult" -execdir cp -R '{}' "/Users/runner/${SDK}-${{ matrix.target }}.xcresult" \;
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: /Users/runner/*.xcresult

  pod-lib-lint-function:
    # Don't run on private repo unless it is a PR.
    needs: check
    if: github.repository == 'Firebase/firebase-ios-sdk' && needs.check.outputs.functions_run_job == 'true'
    runs-on: macOS-latest

    strategy:
      matrix:
        target: [ios, tvos, macos]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Bundler
      run: scripts/setup_bundler.sh
    - name: Build and test
      run: |
        if [ -d "/Users/runner/Library/Developer/Xcode/DerivedData" ]; then
        rm -r /Users/runner/Library/Developer/Xcode/DerivedData/*
        fi
        scripts/third_party/travis/retry.sh scripts/pod_lib_lint.rb FirebaseFunctions.podspec --platforms=${{ matrix.target }} --test-specs=unit
        find /Users/runner/Library/Developer/Xcode/DerivedData -regex ".*/.*\.xcresult" -exec echo {} \;
  create_report:
    needs: [pod-lib-lint-function, pod-lib-lint-database]
    if: always()
    runs-on: macOS-latest
    steps:
      - uses: actions/download-artifact@v2
        id: download
        with:
          path: /Users/runner/test
      - name: display results
        run: |
          [ ! -d "${{steps.download.outputs.download-path}}" ] && echo " Directory does not exist."
          echo "${{steps.download.outputs.download-path}}"
          find "/Users/runner/test" -print -regex ".*/.*\.xcresult" -exec xcrun xccov view --report {} \;
